import { randomInt } from "node:crypto";

const ADJECTIVES = [
  "airy",
  "amber",
  "beige",
  "bouncy",
  "breezy",
  "bright",
  "brisk",
  "bubbly",
  "calm",
  "cheeky",
  "chipper",
  "chummy",
  "clever",
  "cloudy",
  "cozy",
  "coral",
  "crafty",
  "crispy",
  "dandy",
  "daring",
  "dapper",
  "dewy",
  "dreamy",
  "dusty",
  "eager",
  "easy",
  "electric",
  "fancy",
  "feathery",
  "fizzy",
  "fluffy",
  "forest",
  "fresh",
  "frosty",
  "gentle",
  "giddy",
  "giggly",
  "glimmer",
  "glowy",
  "golden",
  "happy",
  "hazy",
  "honey",
  "jaunty",
  "jazzy",
  "jolly",
  "jumpy",
  "kind",
  "light",
  "lively",
  "lofty",
  "lucky",
  "luminous",
  "mellow",
  "merry",
  "misty",
  "moonlit",
  "mossy",
  "neat",
  "nimble",
  "peppy",
  "perky",
  "playful",
  "plucky",
  "polished",
  "pouncy",
  "quick",
  "quirky",
  "radiant",
  "rapid",
  "rosy",
  "rustic",
  "sassy",
  "shiny",
  "silky",
  "sleepy",
  "sneaky",
  "snappy",
  "soft",
  "sparkly",
  "sprightly",
  "spruce",
  "starry",
  "steady",
  "sunny",
  "swirly",
  "swift",
  "tidy",
  "toasty",
  "twinkly",
  "upbeat",
  "velvety",
  "vivid",
  "warm",
  "wavy",
  "whimsical",
  "wild",
  "witty",
  "zany",
  "zesty"
] as const;

const NOUNS = [
  "alpaca",
  "anchor",
  "apple",
  "badger",
  "bagel",
  "balloon",
  "banana",
  "beetle",
  "berry",
  "biscuit",
  "blossom",
  "brook",
  "bunny",
  "cactus",
  "candle",
  "carrot",
  "cherry",
  "clover",
  "comet",
  "cookie",
  "cricket",
  "croissant",
  "daisy",
  "dolphin",
  "donut",
  "drizzle",
  "dumpling",
  "feather",
  "fern",
  "firefly",
  "flannel",
  "flower",
  "frog",
  "glacier",
  "grape",
  "hammock",
  "hamster",
  "harbor",
  "hedgehog",
  "island",
  "jellybean",
  "kite",
  "lantern",
  "lemon",
  "llama",
  "mango",
  "maple",
  "marshmallow",
  "meadow",
  "melon",
  "mitten",
  "moonbeam",
  "moose",
  "muffin",
  "mushroom",
  "noodle",
  "olive",
  "otter",
  "pancake",
  "peach",
  "pear",
  "pebble",
  "penguin",
  "pepper",
  "pickle",
  "pigeon",
  "pinecone",
  "planet",
  "plum",
  "pocket",
  "potato",
  "pretzel",
  "pumpkin",
  "rabbit",
  "rainbow",
  "river",
  "rocket",
  "sailboat",
  "seashell",
  "sketch",
  "snail",
  "soda",
  "sparrow",
  "sprinkle",
  "squirrel",
  "starfish",
  "sunrise",
  "taco",
  "teacup",
  "thistle",
  "tomato",
  "tulip",
  "turnip",
  "violet",
  "waffle",
  "walnut",
  "willow",
  "window",
  "yogurt",
  "zebra"
] as const;

const BLOCKED_WORDS = new Set<string>([]);
const BLOCKED_ALIASES = new Set<string>([]);
const SEARCH_CODE_SUFFIX_SIZE = 100;

function pickRandom<T>(items: readonly T[]): T {
  return items[randomInt(items.length)]!;
}

function isAllowedAlias(alias: string): boolean {
  if (BLOCKED_ALIASES.has(alias)) {
    return false;
  }

  return alias
    .split("-")
    .every((part) => !BLOCKED_WORDS.has(part));
}

export function generateMemorableEventSearchCode(): string {
  for (let attempt = 0; attempt < 50; attempt += 1) {
    const suffix = randomInt(SEARCH_CODE_SUFFIX_SIZE).toString().padStart(2, "0");
    const candidate = `${pickRandom(ADJECTIVES)}-${pickRandom(NOUNS)}-${suffix}`;

    if (isAllowedAlias(candidate)) {
      return candidate;
    }
  }

  throw new Error("Det gick inte att skapa ett nytt sök-ID.");
}

export function getMemorableEventSearchCodeSpaceSize(): number {
  return ADJECTIVES.length * NOUNS.length * SEARCH_CODE_SUFFIX_SIZE;
}
